# Generated by Django 4.2.2 on 2023-06-16 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_category_options_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.category'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='store_link',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.category'),
        ),
    ]
