# Generated by Django 4.2.2 on 2023-06-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_category_alter_coupon_store_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='external_link',
            field=models.URLField(default=''),
        ),
    ]
