# Generated by Django 4.2.2 on 2023-06-17 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('coupon', '0007_alter_store_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.DeleteModel(
            name='CouponPageGalleryImage',
        ),
    ]
