# Generated by Django 4.2.2 on 2023-06-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0008_coupon_featured_image_delete_couponpagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
