# Generated by Django 4.2.3 on 2023-09-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0009_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='template',
            field=models.CharField(choices=[('store_template_a.html', 'Template A'), ('store_template_b.html', 'Template B')], default='store_template_a.html', max_length=255),
        ),
    ]
