# Generated by Django 4.2.3 on 2023-09-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0017_remove_store_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='template',
            field=models.CharField(choices=[('store/store_page.html', 'Template Box'), ('store/store_page_line.html', 'Template Lines')], default='store/store_page.html', max_length=255),
        ),
    ]
