# Generated by Django 4.2.3 on 2023-10-04 00:46

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0018_store_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
