# Generated by Django 4.2.3 on 2023-10-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0019_store_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='description',
            new_name='descriptions',
        ),
    ]
