# Generated by Django 4.2.3 on 2023-10-04 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0020_rename_description_store_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='descriptions',
            new_name='description',
        ),
    ]
