# Generated by Django 4.2.3 on 2023-10-04 04:04

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0021_rename_descriptions_store_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', wagtail.fields.RichTextField()),
            ],
        ),
    ]
