# Generated by Django 4.2.3 on 2023-10-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0022_accordionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accordion_items',
            field=models.ManyToManyField(blank=True, to='coupon.accordionitem'),
        ),
    ]
