# Generated by Django 4.2.3 on 2023-10-04 04:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0024_faq_remove_store_accordion_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='store',
        ),
        migrations.AddField(
            model_name='store',
            name='faqs',
            field=models.ManyToManyField(blank=True, to='coupon.faq'),
        ),
        migrations.CreateModel(
            name='InlineFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.faq')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='coupon.store')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
