# Generated by Django 4.2.3 on 2023-10-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0025_remove_faq_store_store_faqs_inlinefaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inlinefaq',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='inlinefaq',
            name='page',
        ),
        migrations.RemoveField(
            model_name='store',
            name='faqs',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='InlineFAQ',
        ),
    ]
