# Generated by Django 4.2.3 on 2023-10-04 04:35

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0026_remove_inlinefaq_faq_remove_inlinefaq_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accordion',
            field=wagtail.fields.StreamField([('accordion', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.RichTextBlock())]))], blank=True, use_json_field=True),
        ),
    ]
