# Generated by Django 4.2.3 on 2023-10-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0027_store_accordion'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='index_page',
            field=models.BooleanField(default=True, help_text='Check this to allow indexing of the page.'),
        ),
    ]
