# Generated by Django 4.2.3 on 2023-10-26 23:01

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0030_blogpage_standardpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='index_page',
            field=models.BooleanField(default=True, help_text='Check this to allow indexing of the page.'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='accordion',
            field=wagtail.fields.StreamField([('accordion', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.RichTextBlock())]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='index_page',
            field=models.BooleanField(default=True, help_text='Check this to allow indexing of the page.'),
        ),
    ]
