# Generated by Django 4.2.3 on 2023-11-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('coupon', '0032_blogindexpage_blogpostpage_delete_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Upload the store logo image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Upload the coupon image. If not provided, the store image will be used as default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
