# Generated by Django 4.2.3 on 2023-11-13 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('coupon', '0033_store_logo_alter_coupon_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Upload the store logo image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
